from enum import Enum


class InterviewStage(str, Enum):
    REQUIREMENTS = "REQUIREMENTS"
    CAPACITY_ESTIMATION = "CAPACITY_ESTIMATION"
    HIGH_LEVEL_DESIGN = "HIGH_LEVEL_DESIGN"
    DEEP_DIVE = "DEEP_DIVE"
    BOTTLENECKS = "BOTTLENECKS"
    FINAL_REVIEW = "FINAL_REVIEW"